site_name: Introducción git
markdown_extensions:
  - admonition
theme:
        name: 'material'
nav:
  - 'index.md'
  - 'instalacion.md'
  - 'configuracion_git.md'
  - 'github.md'
  - 'usobasico.md'
  - 'ramas.md'